#!/bin/bash

replacement=""
replacement=""
replacement=""

read -p 'Puu.sh API Key: ' key

replacement=s/PUUSH_API_KEY=.*/PUUSH_API_KEY=\"$key\"/

sed -i $replacement puush

read -p 'Filepath to save to: ' path

replacement=s@SAVE_DIR=.*@SAVE_DIR=\"$path\"@

sed -i $replacement puush

read -p 'Screenshot command: ' scrn_cmd

replacement=s@SCREEN_CMD=.*@SCREEN_CMD=\"$scrn_cmd\"@

sed -i "$replacement" puush

echo ' '

echo 'Configuration complete. Installing...'

cp -v puush /usr/bin

chmod +x /usr/bin/puush

echo ' '

echo 'Finished.'